### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by mapehe** [ToukoH/OopJatko#1]
I finally found a replacement sub-transitive Brelliea multiplexer, but i can’t pinpoint what model this is. Guy wants 6800 for it, or he said he’d take a modulating brillion scope for trade. What I can’t tell is the co-processor type to determine if it’s a fair price. I want to say it’s a super-core protohedron model with a quantum duel-tunneling gigatropic induction cache, but it was dark and a few numbers off the serial number was scratched off. Any ideas?

**Comment by ToukoH** [comment]
If you look closely, it's a Z3X8 model, and an early production one at that. The manifold plexor on the right hand side is missing the tell-tale mechahadron conduit indicator that would accompany the consumer run of the X8 model. Honestly, unless you want a little piece of VX history to show off, I'd pass because you'd find incompatibility with most modern quantumhexes.
